name: Simple Workflow

on:
  push:
    branches:
      - main

jobs:
  run-steps:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run a basic command
        run: echo "Hello, GitHub Actions!"
